// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: PPG_UI

#ifndef _PPG_UI_UI_H
#define _PPG_UI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "ui_Screen1.h"
#include "ui_Screen2.h"
#include "ui_Screen3.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_grid_png);    // assets/grid.png
LV_IMG_DECLARE(ui_img_posisistop_png);    // assets/posisiStop.png
LV_IMG_DECLARE(ui_img_posisistart_png);    // assets/posisiStart.png
LV_IMG_DECLARE(ui_img_riwayat_png);    // assets/riwayat.png
LV_IMG_DECLARE(ui_img_user_png);    // assets/user.png
LV_IMG_DECLARE(ui_img_hearticon_png);    // assets/heartIcon.png
LV_IMG_DECLARE(ui_img_clockicon_png);    // assets/clockIcon.png
LV_IMG_DECLARE(ui_img_batteryicon_png);    // assets/batteryIcon.png
LV_IMG_DECLARE(ui_img_logo_kmnksjkt3_png);    // assets/logo_kmnksjkt3.png
LV_IMG_DECLARE(ui_img_buang_png);    // assets/buang.png
LV_IMG_DECLARE(ui_img_back_png);    // assets/back.png
LV_IMG_DECLARE(ui_img_user_logo_png);    // assets/user_logo.png
LV_IMG_DECLARE(ui_img_ceklis_png);    // assets/ceklis.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
