// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: PPG_UI

#include "ui.h"

lv_obj_t * ui_Screen3 = NULL;
lv_obj_t * ui_Panel2 = NULL;
lv_obj_t * ui_Dropdown2 = NULL;
lv_obj_t * ui_TextArea7 = NULL;
lv_obj_t * ui_TextArea2 = NULL;
lv_obj_t * ui_TextArea6 = NULL;
lv_obj_t * ui_TextArea3 = NULL;
lv_obj_t * ui_Panel12 = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_penggunaText6 = NULL;
lv_obj_t * ui_penggunaText5 = NULL;
lv_obj_t * ui_penggunaText4 = NULL;
lv_obj_t * ui_penggunaText3 = NULL;
lv_obj_t * ui_penggunaText2 = NULL;
lv_obj_t * ui_Panel6 = NULL;
lv_obj_t * ui_namaText3 = NULL;
lv_obj_t * ui_Button5 = NULL;
lv_obj_t * ui_ImgButton1 = NULL;
lv_obj_t * ui_Keyboard3 = NULL;
lv_obj_t * ui_Panel13 = NULL;
// event funtions
void ui_event_TextArea7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard3,  ui_TextArea7);
        _ui_flag_modify(ui_Keyboard3, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}

void ui_event_TextArea2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard3,  ui_TextArea2);
        _ui_flag_modify(ui_Keyboard3, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}

void ui_event_TextArea6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard3,  ui_TextArea6);
        _ui_flag_modify(ui_Keyboard3, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}

void ui_event_TextArea3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Keyboard3, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_keyboard_set_target(ui_Keyboard3,  ui_TextArea3);
    }
}

void ui_event_ImgButton1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen1_screen_init);
    }
}

// build funtions

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen3, lv_color_hex(0x111828), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_Screen3);
    lv_obj_set_width(ui_Panel2, 513);
    lv_obj_set_height(ui_Panel2, 354);
    lv_obj_set_x(ui_Panel2, 123);
    lv_obj_set_y(ui_Panel2, 31);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLL_CHAIN);      /// Flags
    lv_obj_set_scrollbar_mode(ui_Panel2, LV_SCROLLBAR_MODE_ON);
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Dropdown2 = lv_dropdown_create(ui_Panel2);
    lv_dropdown_set_options(ui_Dropdown2, "Laki - laki \nPerempuan\n");
    lv_obj_set_width(ui_Dropdown2, 202);
    lv_obj_set_height(ui_Dropdown2, 45);
    lv_obj_set_x(ui_Dropdown2, 129);
    lv_obj_set_y(ui_Dropdown2, -8);
    lv_obj_set_align(ui_Dropdown2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_bg_color(ui_Dropdown2, lv_color_hex(0x202938), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Dropdown2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_Dropdown2), lv_color_hex(0x202938),  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_Dropdown2), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea7 = lv_textarea_create(ui_Panel2);
    lv_obj_set_width(ui_TextArea7, 202);
    lv_obj_set_height(ui_TextArea7, 45);
    lv_obj_set_x(ui_TextArea7, 129);
    lv_obj_set_y(ui_TextArea7, 72);
    lv_obj_set_align(ui_TextArea7, LV_ALIGN_CENTER);
    lv_textarea_set_accepted_chars(ui_TextArea7, "1234567890");
    lv_textarea_set_max_length(ui_TextArea7, 3);
    lv_textarea_set_placeholder_text(ui_TextArea7, "Masukan Tinggi Badan...");
    lv_obj_set_style_bg_color(ui_TextArea7, lv_color_hex(0x202938), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TextArea7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea2 = lv_textarea_create(ui_Panel2);
    lv_obj_set_width(ui_TextArea2, 365);
    lv_obj_set_height(ui_TextArea2, 45);
    lv_obj_set_x(ui_TextArea2, 45);
    lv_obj_set_y(ui_TextArea2, -105);
    lv_obj_set_align(ui_TextArea2, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea2, "Masukan Nama di sini...");
    lv_obj_set_style_bg_color(ui_TextArea2, lv_color_hex(0x202938), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TextArea2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea6 = lv_textarea_create(ui_Panel2);
    lv_obj_set_width(ui_TextArea6, 248);
    lv_obj_set_height(ui_TextArea6, 45);
    lv_obj_set_x(ui_TextArea6, -104);
    lv_obj_set_y(ui_TextArea6, 72);
    lv_obj_set_align(ui_TextArea6, LV_ALIGN_CENTER);
    lv_textarea_set_accepted_chars(ui_TextArea6, "1234567890");
    lv_textarea_set_max_length(ui_TextArea6, 3);
    lv_textarea_set_placeholder_text(ui_TextArea6, "Masukan Berat Badan...");
    lv_obj_set_style_bg_color(ui_TextArea6, lv_color_hex(0x202938), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TextArea6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea3 = lv_textarea_create(ui_Panel2);
    lv_obj_set_width(ui_TextArea3, 248);
    lv_obj_set_height(ui_TextArea3, 45);
    lv_obj_set_x(ui_TextArea3, -104);
    lv_obj_set_y(ui_TextArea3, -8);
    lv_obj_set_align(ui_TextArea3, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea3, "Masukan Tanggal Lahir...");
    lv_obj_set_style_bg_color(ui_TextArea3, lv_color_hex(0x202938), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TextArea3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel12 = lv_obj_create(ui_Panel2);
    lv_obj_set_width(ui_Panel12, 455);
    lv_obj_set_height(ui_Panel12, 82);
    lv_obj_set_x(ui_Panel12, -1);
    lv_obj_set_y(ui_Panel12, 171);
    lv_obj_set_align(ui_Panel12, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel12, lv_color_hex(0x202938), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel12, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_Panel2);
    lv_img_set_src(ui_Image1, &ui_img_user_logo_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image1, -188);
    lv_obj_set_y(ui_Image1, -112);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image1, 90);

    ui_penggunaText6 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_penggunaText6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_penggunaText6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_penggunaText6, 70);
    lv_obj_set_y(ui_penggunaText6, 33);
    lv_obj_set_align(ui_penggunaText6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_penggunaText6, "Tinggi (cm)");
    lv_obj_set_style_text_color(ui_penggunaText6, lv_color_hex(0xB5B3B3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_penggunaText6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_penggunaText6, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_penggunaText5 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_penggunaText5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_penggunaText5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_penggunaText5, -190);
    lv_obj_set_y(ui_penggunaText5, 33);
    lv_obj_set_align(ui_penggunaText5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_penggunaText5, "Berat (kg)");
    lv_obj_set_style_text_color(ui_penggunaText5, lv_color_hex(0xB5B3B3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_penggunaText5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_penggunaText5, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_penggunaText4 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_penggunaText4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_penggunaText4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_penggunaText4, 57);
    lv_obj_set_y(ui_penggunaText4, -43);
    lv_obj_set_align(ui_penggunaText4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_penggunaText4, "Gender");
    lv_obj_set_style_text_color(ui_penggunaText4, lv_color_hex(0xB5B3B3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_penggunaText4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_penggunaText4, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_penggunaText3 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_penggunaText3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_penggunaText3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_penggunaText3, -179);
    lv_obj_set_y(ui_penggunaText3, -44);
    lv_obj_set_align(ui_penggunaText3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_penggunaText3, "Tanggal Lahir");
    lv_obj_set_style_text_color(ui_penggunaText3, lv_color_hex(0xB5B3B3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_penggunaText3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_penggunaText3, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_penggunaText2 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_penggunaText2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_penggunaText2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_penggunaText2, -70);
    lv_obj_set_y(ui_penggunaText2, -140);
    lv_obj_set_align(ui_penggunaText2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_penggunaText2, "Nama Lengkap");
    lv_obj_set_style_text_color(ui_penggunaText2, lv_color_hex(0xB5B3B3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_penggunaText2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_penggunaText2, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel6 = lv_obj_create(ui_Screen3);
    lv_obj_set_width(ui_Panel6, 823);
    lv_obj_set_height(ui_Panel6, 62);
    lv_obj_set_x(ui_Panel6, -9);
    lv_obj_set_y(ui_Panel6, -210);
    lv_obj_set_align(ui_Panel6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel6, lv_color_hex(0x111828), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel6, lv_color_hex(0x282F3E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel6, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_namaText3 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_namaText3, 116);
    lv_obj_set_height(ui_namaText3, 38);
    lv_obj_set_x(ui_namaText3, 343);
    lv_obj_set_y(ui_namaText3, 8);
    lv_label_set_text(ui_namaText3, "Profil");
    lv_obj_set_style_text_color(ui_namaText3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_namaText3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_namaText3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_namaText3, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button5 = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_Button5, 40);
    lv_obj_set_height(ui_Button5, 40);
    lv_obj_set_x(ui_Button5, 355);
    lv_obj_set_y(ui_Button5, -211);
    lv_obj_set_align(ui_Button5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Button5, &ui_img_ceklis_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButton1 = lv_imgbtn_create(ui_Screen3);
    lv_imgbtn_set_src(ui_ImgButton1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_back_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton1, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_back_png, NULL);
    lv_obj_set_width(ui_ImgButton1, 40);
    lv_obj_set_height(ui_ImgButton1, 40);
    lv_obj_set_x(ui_ImgButton1, -364);
    lv_obj_set_y(ui_ImgButton1, -211);
    lv_obj_set_align(ui_ImgButton1, LV_ALIGN_CENTER);

    ui_Keyboard3 = lv_keyboard_create(ui_Screen3);
    lv_obj_set_width(ui_Keyboard3, 789);
    lv_obj_set_height(ui_Keyboard3, 270);
    lv_obj_set_x(ui_Keyboard3, -1);
    lv_obj_set_y(ui_Keyboard3, 103);
    lv_obj_set_align(ui_Keyboard3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Keyboard3, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_Panel13 = lv_obj_create(ui_Screen3);
    lv_obj_set_width(ui_Panel13, 219);
    lv_obj_set_height(ui_Panel13, 27);
    lv_obj_set_x(ui_Panel13, 1);
    lv_obj_set_y(ui_Panel13, -139);
    lv_obj_set_align(ui_Panel13, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Panel13, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_Panel13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_TextArea7, ui_event_TextArea7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextArea2, ui_event_TextArea2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextArea6, ui_event_TextArea6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextArea3, ui_event_TextArea3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton1, ui_event_ImgButton1, LV_EVENT_ALL, NULL);

}

void ui_Screen3_screen_destroy(void)
{
    if(ui_Screen3) lv_obj_del(ui_Screen3);

    // NULL screen variables
    ui_Screen3 = NULL;
    ui_Panel2 = NULL;
    ui_Dropdown2 = NULL;
    ui_TextArea7 = NULL;
    ui_TextArea2 = NULL;
    ui_TextArea6 = NULL;
    ui_TextArea3 = NULL;
    ui_Panel12 = NULL;
    ui_Image1 = NULL;
    ui_penggunaText6 = NULL;
    ui_penggunaText5 = NULL;
    ui_penggunaText4 = NULL;
    ui_penggunaText3 = NULL;
    ui_penggunaText2 = NULL;
    ui_Panel6 = NULL;
    ui_namaText3 = NULL;
    ui_Button5 = NULL;
    ui_ImgButton1 = NULL;
    ui_Keyboard3 = NULL;
    ui_Panel13 = NULL;

}
