// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: PPG_UI

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_startButton;
extern lv_obj_t * ui_textIntruksi;
extern lv_obj_t * ui_Panel1;
extern void ui_event_riwayatButton(lv_event_t * e);
extern lv_obj_t * ui_riwayatButton;
extern lv_obj_t * ui_ppgChart;
extern lv_obj_t * ui_signalBar;
extern lv_obj_t * ui_actualBatt;
extern lv_obj_t * ui_percentBatt;
extern void ui_event_userButton(lv_event_t * e);
extern lv_obj_t * ui_userButton;
extern lv_obj_t * ui_textTD;
extern lv_obj_t * ui_satuanBPM;
extern lv_obj_t * ui_actualBPM;
extern lv_obj_t * ui_textSinyal;
extern lv_obj_t * ui_actualTime;
extern lv_obj_t * ui_textPPG;
extern lv_obj_t * ui_actualSignal;
extern lv_obj_t * ui_percentSignal;
extern lv_obj_t * ui_satuanTD;
extern lv_obj_t * ui_actualTD;
extern lv_obj_t * ui_heartImg;
extern lv_obj_t * ui_clockImg;
extern lv_obj_t * ui_batteryImg;
extern lv_obj_t * ui_Image3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

