// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: PPG_UI

#ifndef UI_SCREEN3_H
#define UI_SCREEN3_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen3
extern void ui_Screen3_screen_init(void);
extern void ui_Screen3_screen_destroy(void);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Dropdown2;
extern void ui_event_TextArea7(lv_event_t * e);
extern lv_obj_t * ui_TextArea7;
extern void ui_event_TextArea2(lv_event_t * e);
extern lv_obj_t * ui_TextArea2;
extern void ui_event_TextArea6(lv_event_t * e);
extern lv_obj_t * ui_TextArea6;
extern void ui_event_TextArea3(lv_event_t * e);
extern lv_obj_t * ui_TextArea3;
extern lv_obj_t * ui_Panel12;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_penggunaText6;
extern lv_obj_t * ui_penggunaText5;
extern lv_obj_t * ui_penggunaText4;
extern lv_obj_t * ui_penggunaText3;
extern lv_obj_t * ui_penggunaText2;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_namaText3;
extern lv_obj_t * ui_Button5;
extern void ui_event_ImgButton1(lv_event_t * e);
extern lv_obj_t * ui_ImgButton1;
extern lv_obj_t * ui_Keyboard3;
extern lv_obj_t * ui_Panel13;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

