// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: PPG_UI

#include "ui.h"

lv_obj_t * ui_Screen2 = NULL;
lv_obj_t * ui_Panel3 = NULL;
lv_obj_t * ui_Button3 = NULL;
lv_obj_t * ui_namaText2 = NULL;
lv_obj_t * ui_ImgButton3 = NULL;
lv_obj_t * ui_Panel4 = NULL;
lv_obj_t * ui_panelHistory1 = NULL;
lv_obj_t * ui_timeHistory1 = NULL;
lv_obj_t * ui_TDHistory1 = NULL;
lv_obj_t * ui_userHistory1 = NULL;
lv_obj_t * ui_STDHistory1 = NULL;
lv_obj_t * ui_SBPMHisory1 = NULL;
lv_obj_t * ui_BPMHistory1 = NULL;
lv_obj_t * ui_textDot1 = NULL;
lv_obj_t * ui_dateHistory1 = NULL;
lv_obj_t * ui_panelHistory2 = NULL;
lv_obj_t * ui_timeHistory2 = NULL;
lv_obj_t * ui_TDHistory2 = NULL;
lv_obj_t * ui_userHistory2 = NULL;
lv_obj_t * ui_STDHistory2 = NULL;
lv_obj_t * ui_SBPMHisory2 = NULL;
lv_obj_t * ui_BPMHistory2 = NULL;
lv_obj_t * ui_textDot2 = NULL;
lv_obj_t * ui_dateHistory2 = NULL;
lv_obj_t * ui_panelHistory3 = NULL;
lv_obj_t * ui_timeHistory3 = NULL;
lv_obj_t * ui_TDHistory3 = NULL;
lv_obj_t * ui_userHistory3 = NULL;
lv_obj_t * ui_STDHistory3 = NULL;
lv_obj_t * ui_SBPMHisory3 = NULL;
lv_obj_t * ui_BPMHistory3 = NULL;
lv_obj_t * ui_textDot3 = NULL;
lv_obj_t * ui_dateHistory3 = NULL;
lv_obj_t * ui_panelHistory4 = NULL;
lv_obj_t * ui_timeHistory4 = NULL;
lv_obj_t * ui_TDHistory4 = NULL;
lv_obj_t * ui_userHistory4 = NULL;
lv_obj_t * ui_STDHistory4 = NULL;
lv_obj_t * ui_SBPMHisory4 = NULL;
lv_obj_t * ui_BPMHistory4 = NULL;
lv_obj_t * ui_textDot4 = NULL;
lv_obj_t * ui_dateHistory4 = NULL;
lv_obj_t * ui_panelHistory5 = NULL;
lv_obj_t * ui_timeHistory5 = NULL;
lv_obj_t * ui_TDHistory5 = NULL;
lv_obj_t * ui_userHistory5 = NULL;
lv_obj_t * ui_STDHistory5 = NULL;
lv_obj_t * ui_SBPMHisory5 = NULL;
lv_obj_t * ui_BPMHistory5 = NULL;
lv_obj_t * ui_textDot5 = NULL;
lv_obj_t * ui_dateHistory5 = NULL;
// event funtions
void ui_event_ImgButton3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen1_screen_init);
    }
}

// build funtions

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_CHAIN);      /// Flags
    lv_obj_set_scrollbar_mode(ui_Screen2, LV_SCROLLBAR_MODE_ACTIVE);
    lv_obj_set_style_bg_color(ui_Screen2, lv_color_hex(0x111828), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_Panel3, 823);
    lv_obj_set_height(ui_Panel3, 62);
    lv_obj_set_x(ui_Panel3, -9);
    lv_obj_set_y(ui_Panel3, -210);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0x111828), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel3, lv_color_hex(0x282F3E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button3 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_Button3, 40);
    lv_obj_set_height(ui_Button3, 40);
    lv_obj_set_x(ui_Button3, 355);
    lv_obj_set_y(ui_Button3, -211);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Button3, &ui_img_buang_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_namaText2 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_namaText2, 151);
    lv_obj_set_height(ui_namaText2, 38);
    lv_obj_set_x(ui_namaText2, 321);
    lv_obj_set_y(ui_namaText2, 8);
    lv_label_set_text(ui_namaText2, "Riwayat");
    lv_obj_set_style_text_color(ui_namaText2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_namaText2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_namaText2, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_namaText2, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButton3 = lv_imgbtn_create(ui_Screen2);
    lv_imgbtn_set_src(ui_ImgButton3, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_back_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton3, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_back_png, NULL);
    lv_obj_set_width(ui_ImgButton3, 40);
    lv_obj_set_height(ui_ImgButton3, 40);
    lv_obj_set_x(ui_ImgButton3, -364);
    lv_obj_set_y(ui_ImgButton3, -214);
    lv_obj_set_align(ui_ImgButton3, LV_ALIGN_CENTER);

    ui_Panel4 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_Panel4, 690);
    lv_obj_set_height(ui_Panel4, 398);
    lv_obj_set_x(ui_Panel4, -1);
    lv_obj_set_y(ui_Panel4, 30);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel4, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Panel4, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLL_CHAIN);      /// Flags
    lv_obj_set_scroll_snap_x(ui_Panel4, LV_SCROLL_SNAP_START);
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_panelHistory1 = lv_obj_create(ui_Panel4);
    lv_obj_set_width(ui_panelHistory1, 600);
    lv_obj_set_height(ui_panelHistory1, 120);
    lv_obj_set_x(ui_panelHistory1, 2);
    lv_obj_set_y(ui_panelHistory1, 173);
    lv_obj_set_align(ui_panelHistory1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_panelHistory1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_panelHistory1, lv_color_hex(0x121421), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panelHistory1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_panelHistory1, lv_color_hex(0x121421), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_panelHistory1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_timeHistory1 = lv_label_create(ui_panelHistory1);
    lv_obj_set_width(ui_timeHistory1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_timeHistory1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_timeHistory1, 250);
    lv_obj_set_y(ui_timeHistory1, 2);
    lv_obj_set_align(ui_timeHistory1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_timeHistory1, "00.00");
    lv_obj_set_style_text_color(ui_timeHistory1, lv_color_hex(0xD5D5D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_timeHistory1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_timeHistory1, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_timeHistory1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TDHistory1 = lv_label_create(ui_panelHistory1);
    lv_obj_set_width(ui_TDHistory1, 83);
    lv_obj_set_height(ui_TDHistory1, 20);
    lv_obj_set_x(ui_TDHistory1, -10);
    lv_obj_set_y(ui_TDHistory1, 6);
    lv_label_set_text(ui_TDHistory1, "--/--");
    lv_obj_set_style_text_color(ui_TDHistory1, lv_color_hex(0x00FF9A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TDHistory1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_TDHistory1, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TDHistory1, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_userHistory1 = lv_label_create(ui_panelHistory1);
    lv_obj_set_width(ui_userHistory1, 175);
    lv_obj_set_height(ui_userHistory1, 17);
    lv_obj_set_x(ui_userHistory1, 374);
    lv_obj_set_y(ui_userHistory1, -5);
    lv_label_set_text(ui_userHistory1, "Admin");
    lv_obj_set_style_text_color(ui_userHistory1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_userHistory1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_userHistory1, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_userHistory1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_STDHistory1 = lv_label_create(ui_panelHistory1);
    lv_obj_set_width(ui_STDHistory1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_STDHistory1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_STDHistory1, -168);
    lv_obj_set_y(ui_STDHistory1, -17);
    lv_obj_set_align(ui_STDHistory1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_STDHistory1, "mg/dL");
    lv_obj_set_style_text_color(ui_STDHistory1, lv_color_hex(0xD5D5D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_STDHistory1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_STDHistory1, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_STDHistory1, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SBPMHisory1 = lv_label_create(ui_panelHistory1);
    lv_obj_set_width(ui_SBPMHisory1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SBPMHisory1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SBPMHisory1, -176);
    lv_obj_set_y(ui_SBPMHisory1, 26);
    lv_obj_set_align(ui_SBPMHisory1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SBPMHisory1, "BPM");
    lv_obj_set_style_text_color(ui_SBPMHisory1, lv_color_hex(0xD5D5D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SBPMHisory1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_SBPMHisory1, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SBPMHisory1, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BPMHistory1 = lv_label_create(ui_panelHistory1);
    lv_obj_set_width(ui_BPMHistory1, 43);
    lv_obj_set_height(ui_BPMHistory1, 20);
    lv_obj_set_x(ui_BPMHistory1, 26);
    lv_obj_set_y(ui_BPMHistory1, 50);
    lv_label_set_text(ui_BPMHistory1, "--");
    lv_obj_set_style_text_color(ui_BPMHistory1, lv_color_hex(0xF56570), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BPMHistory1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_BPMHistory1, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BPMHistory1, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_textDot1 = lv_label_create(ui_panelHistory1);
    lv_obj_set_width(ui_textDot1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_textDot1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_textDot1, 220);
    lv_obj_set_y(ui_textDot1, -6);
    lv_obj_set_align(ui_textDot1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_textDot1, ".");
    lv_obj_set_style_text_color(ui_textDot1, lv_color_hex(0xD5D5D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_textDot1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_textDot1, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_textDot1, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dateHistory1 = lv_label_create(ui_panelHistory1);
    lv_obj_set_width(ui_dateHistory1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dateHistory1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dateHistory1, 185);
    lv_obj_set_y(ui_dateHistory1, 1);
    lv_obj_set_align(ui_dateHistory1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dateHistory1, "14 mar");
    lv_obj_set_style_text_color(ui_dateHistory1, lv_color_hex(0xD5D5D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_dateHistory1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_dateHistory1, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_dateHistory1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_panelHistory2 = lv_obj_create(ui_Panel4);
    lv_obj_set_width(ui_panelHistory2, 600);
    lv_obj_set_height(ui_panelHistory2, 120);
    lv_obj_set_x(ui_panelHistory2, 2);
    lv_obj_set_y(ui_panelHistory2, 173);
    lv_obj_set_align(ui_panelHistory2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_panelHistory2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_panelHistory2, lv_color_hex(0x121421), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panelHistory2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_panelHistory2, lv_color_hex(0x121421), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_panelHistory2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_timeHistory2 = lv_label_create(ui_panelHistory2);
    lv_obj_set_width(ui_timeHistory2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_timeHistory2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_timeHistory2, 250);
    lv_obj_set_y(ui_timeHistory2, 2);
    lv_obj_set_align(ui_timeHistory2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_timeHistory2, "00.00");
    lv_obj_set_style_text_color(ui_timeHistory2, lv_color_hex(0xD5D5D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_timeHistory2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_timeHistory2, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_timeHistory2, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TDHistory2 = lv_label_create(ui_panelHistory2);
    lv_obj_set_width(ui_TDHistory2, 83);
    lv_obj_set_height(ui_TDHistory2, 20);
    lv_obj_set_x(ui_TDHistory2, -10);
    lv_obj_set_y(ui_TDHistory2, 6);
    lv_label_set_text(ui_TDHistory2, "--/--");
    lv_obj_set_style_text_color(ui_TDHistory2, lv_color_hex(0x00FF9A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TDHistory2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_TDHistory2, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TDHistory2, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_userHistory2 = lv_label_create(ui_panelHistory2);
    lv_obj_set_width(ui_userHistory2, 175);
    lv_obj_set_height(ui_userHistory2, 17);
    lv_obj_set_x(ui_userHistory2, 374);
    lv_obj_set_y(ui_userHistory2, -5);
    lv_label_set_text(ui_userHistory2, "Admin");
    lv_obj_set_style_text_color(ui_userHistory2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_userHistory2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_userHistory2, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_userHistory2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_STDHistory2 = lv_label_create(ui_panelHistory2);
    lv_obj_set_width(ui_STDHistory2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_STDHistory2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_STDHistory2, -168);
    lv_obj_set_y(ui_STDHistory2, -17);
    lv_obj_set_align(ui_STDHistory2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_STDHistory2, "mg/dL");
    lv_obj_set_style_text_color(ui_STDHistory2, lv_color_hex(0xD5D5D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_STDHistory2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_STDHistory2, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_STDHistory2, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SBPMHisory2 = lv_label_create(ui_panelHistory2);
    lv_obj_set_width(ui_SBPMHisory2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SBPMHisory2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SBPMHisory2, -176);
    lv_obj_set_y(ui_SBPMHisory2, 26);
    lv_obj_set_align(ui_SBPMHisory2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SBPMHisory2, "BPM");
    lv_obj_set_style_text_color(ui_SBPMHisory2, lv_color_hex(0xD5D5D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SBPMHisory2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_SBPMHisory2, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SBPMHisory2, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BPMHistory2 = lv_label_create(ui_panelHistory2);
    lv_obj_set_width(ui_BPMHistory2, 43);
    lv_obj_set_height(ui_BPMHistory2, 20);
    lv_obj_set_x(ui_BPMHistory2, 26);
    lv_obj_set_y(ui_BPMHistory2, 50);
    lv_label_set_text(ui_BPMHistory2, "--");
    lv_obj_set_style_text_color(ui_BPMHistory2, lv_color_hex(0xF56570), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BPMHistory2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_BPMHistory2, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BPMHistory2, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_textDot2 = lv_label_create(ui_panelHistory2);
    lv_obj_set_width(ui_textDot2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_textDot2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_textDot2, 220);
    lv_obj_set_y(ui_textDot2, -6);
    lv_obj_set_align(ui_textDot2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_textDot2, ".");
    lv_obj_set_style_text_color(ui_textDot2, lv_color_hex(0xD5D5D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_textDot2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_textDot2, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_textDot2, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dateHistory2 = lv_label_create(ui_panelHistory2);
    lv_obj_set_width(ui_dateHistory2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dateHistory2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dateHistory2, 185);
    lv_obj_set_y(ui_dateHistory2, 1);
    lv_obj_set_align(ui_dateHistory2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dateHistory2, "14 mar");
    lv_obj_set_style_text_color(ui_dateHistory2, lv_color_hex(0xD5D5D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_dateHistory2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_dateHistory2, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_dateHistory2, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_panelHistory3 = lv_obj_create(ui_Panel4);
    lv_obj_set_width(ui_panelHistory3, 600);
    lv_obj_set_height(ui_panelHistory3, 120);
    lv_obj_set_x(ui_panelHistory3, 2);
    lv_obj_set_y(ui_panelHistory3, 173);
    lv_obj_set_align(ui_panelHistory3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_panelHistory3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_panelHistory3, lv_color_hex(0x121421), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panelHistory3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_panelHistory3, lv_color_hex(0x121421), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_panelHistory3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_timeHistory3 = lv_label_create(ui_panelHistory3);
    lv_obj_set_width(ui_timeHistory3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_timeHistory3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_timeHistory3, 250);
    lv_obj_set_y(ui_timeHistory3, 2);
    lv_obj_set_align(ui_timeHistory3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_timeHistory3, "00.00");
    lv_obj_set_style_text_color(ui_timeHistory3, lv_color_hex(0xD5D5D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_timeHistory3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_timeHistory3, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_timeHistory3, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TDHistory3 = lv_label_create(ui_panelHistory3);
    lv_obj_set_width(ui_TDHistory3, 83);
    lv_obj_set_height(ui_TDHistory3, 20);
    lv_obj_set_x(ui_TDHistory3, -10);
    lv_obj_set_y(ui_TDHistory3, 6);
    lv_label_set_text(ui_TDHistory3, "--/--");
    lv_obj_set_style_text_color(ui_TDHistory3, lv_color_hex(0x00FF9A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TDHistory3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_TDHistory3, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TDHistory3, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_userHistory3 = lv_label_create(ui_panelHistory3);
    lv_obj_set_width(ui_userHistory3, 175);
    lv_obj_set_height(ui_userHistory3, 17);
    lv_obj_set_x(ui_userHistory3, 374);
    lv_obj_set_y(ui_userHistory3, -5);
    lv_label_set_text(ui_userHistory3, "Admin");
    lv_obj_set_style_text_color(ui_userHistory3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_userHistory3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_userHistory3, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_userHistory3, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_STDHistory3 = lv_label_create(ui_panelHistory3);
    lv_obj_set_width(ui_STDHistory3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_STDHistory3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_STDHistory3, -168);
    lv_obj_set_y(ui_STDHistory3, -17);
    lv_obj_set_align(ui_STDHistory3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_STDHistory3, "mg/dL");
    lv_obj_set_style_text_color(ui_STDHistory3, lv_color_hex(0xD5D5D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_STDHistory3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_STDHistory3, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_STDHistory3, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SBPMHisory3 = lv_label_create(ui_panelHistory3);
    lv_obj_set_width(ui_SBPMHisory3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SBPMHisory3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SBPMHisory3, -176);
    lv_obj_set_y(ui_SBPMHisory3, 26);
    lv_obj_set_align(ui_SBPMHisory3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SBPMHisory3, "BPM");
    lv_obj_set_style_text_color(ui_SBPMHisory3, lv_color_hex(0xD5D5D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SBPMHisory3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_SBPMHisory3, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SBPMHisory3, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BPMHistory3 = lv_label_create(ui_panelHistory3);
    lv_obj_set_width(ui_BPMHistory3, 43);
    lv_obj_set_height(ui_BPMHistory3, 20);
    lv_obj_set_x(ui_BPMHistory3, 26);
    lv_obj_set_y(ui_BPMHistory3, 50);
    lv_label_set_text(ui_BPMHistory3, "--");
    lv_obj_set_style_text_color(ui_BPMHistory3, lv_color_hex(0xF56570), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BPMHistory3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_BPMHistory3, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BPMHistory3, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_textDot3 = lv_label_create(ui_panelHistory3);
    lv_obj_set_width(ui_textDot3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_textDot3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_textDot3, 220);
    lv_obj_set_y(ui_textDot3, -6);
    lv_obj_set_align(ui_textDot3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_textDot3, ".");
    lv_obj_set_style_text_color(ui_textDot3, lv_color_hex(0xD5D5D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_textDot3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_textDot3, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_textDot3, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dateHistory3 = lv_label_create(ui_panelHistory3);
    lv_obj_set_width(ui_dateHistory3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dateHistory3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dateHistory3, 185);
    lv_obj_set_y(ui_dateHistory3, 1);
    lv_obj_set_align(ui_dateHistory3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dateHistory3, "14 mar");
    lv_obj_set_style_text_color(ui_dateHistory3, lv_color_hex(0xD5D5D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_dateHistory3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_dateHistory3, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_dateHistory3, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_panelHistory4 = lv_obj_create(ui_Panel4);
    lv_obj_set_width(ui_panelHistory4, 600);
    lv_obj_set_height(ui_panelHistory4, 120);
    lv_obj_set_x(ui_panelHistory4, 2);
    lv_obj_set_y(ui_panelHistory4, 173);
    lv_obj_set_align(ui_panelHistory4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_panelHistory4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_panelHistory4, lv_color_hex(0x121421), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panelHistory4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_panelHistory4, lv_color_hex(0x121421), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_panelHistory4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_timeHistory4 = lv_label_create(ui_panelHistory4);
    lv_obj_set_width(ui_timeHistory4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_timeHistory4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_timeHistory4, 250);
    lv_obj_set_y(ui_timeHistory4, 2);
    lv_obj_set_align(ui_timeHistory4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_timeHistory4, "00.00");
    lv_obj_set_style_text_color(ui_timeHistory4, lv_color_hex(0xD5D5D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_timeHistory4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_timeHistory4, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_timeHistory4, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TDHistory4 = lv_label_create(ui_panelHistory4);
    lv_obj_set_width(ui_TDHistory4, 83);
    lv_obj_set_height(ui_TDHistory4, 20);
    lv_obj_set_x(ui_TDHistory4, -10);
    lv_obj_set_y(ui_TDHistory4, 6);
    lv_label_set_text(ui_TDHistory4, "--/--");
    lv_obj_set_style_text_color(ui_TDHistory4, lv_color_hex(0x00FF9A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TDHistory4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_TDHistory4, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TDHistory4, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_userHistory4 = lv_label_create(ui_panelHistory4);
    lv_obj_set_width(ui_userHistory4, 175);
    lv_obj_set_height(ui_userHistory4, 17);
    lv_obj_set_x(ui_userHistory4, 374);
    lv_obj_set_y(ui_userHistory4, -5);
    lv_label_set_text(ui_userHistory4, "Admin");
    lv_obj_set_style_text_color(ui_userHistory4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_userHistory4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_userHistory4, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_userHistory4, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_STDHistory4 = lv_label_create(ui_panelHistory4);
    lv_obj_set_width(ui_STDHistory4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_STDHistory4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_STDHistory4, -168);
    lv_obj_set_y(ui_STDHistory4, -17);
    lv_obj_set_align(ui_STDHistory4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_STDHistory4, "mg/dL");
    lv_obj_set_style_text_color(ui_STDHistory4, lv_color_hex(0xD5D5D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_STDHistory4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_STDHistory4, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_STDHistory4, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SBPMHisory4 = lv_label_create(ui_panelHistory4);
    lv_obj_set_width(ui_SBPMHisory4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SBPMHisory4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SBPMHisory4, -176);
    lv_obj_set_y(ui_SBPMHisory4, 26);
    lv_obj_set_align(ui_SBPMHisory4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SBPMHisory4, "BPM");
    lv_obj_set_style_text_color(ui_SBPMHisory4, lv_color_hex(0xD5D5D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SBPMHisory4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_SBPMHisory4, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SBPMHisory4, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BPMHistory4 = lv_label_create(ui_panelHistory4);
    lv_obj_set_width(ui_BPMHistory4, 43);
    lv_obj_set_height(ui_BPMHistory4, 20);
    lv_obj_set_x(ui_BPMHistory4, 26);
    lv_obj_set_y(ui_BPMHistory4, 50);
    lv_label_set_text(ui_BPMHistory4, "--");
    lv_obj_set_style_text_color(ui_BPMHistory4, lv_color_hex(0xF56570), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BPMHistory4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_BPMHistory4, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BPMHistory4, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_textDot4 = lv_label_create(ui_panelHistory4);
    lv_obj_set_width(ui_textDot4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_textDot4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_textDot4, 220);
    lv_obj_set_y(ui_textDot4, -6);
    lv_obj_set_align(ui_textDot4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_textDot4, ".");
    lv_obj_set_style_text_color(ui_textDot4, lv_color_hex(0xD5D5D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_textDot4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_textDot4, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_textDot4, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dateHistory4 = lv_label_create(ui_panelHistory4);
    lv_obj_set_width(ui_dateHistory4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dateHistory4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dateHistory4, 185);
    lv_obj_set_y(ui_dateHistory4, 1);
    lv_obj_set_align(ui_dateHistory4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dateHistory4, "14 mar");
    lv_obj_set_style_text_color(ui_dateHistory4, lv_color_hex(0xD5D5D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_dateHistory4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_dateHistory4, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_dateHistory4, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_panelHistory5 = lv_obj_create(ui_Panel4);
    lv_obj_set_width(ui_panelHistory5, 600);
    lv_obj_set_height(ui_panelHistory5, 120);
    lv_obj_set_x(ui_panelHistory5, 2);
    lv_obj_set_y(ui_panelHistory5, 173);
    lv_obj_set_align(ui_panelHistory5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_panelHistory5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_panelHistory5, lv_color_hex(0x121421), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panelHistory5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_panelHistory5, lv_color_hex(0x121421), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_panelHistory5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_timeHistory5 = lv_label_create(ui_panelHistory5);
    lv_obj_set_width(ui_timeHistory5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_timeHistory5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_timeHistory5, 250);
    lv_obj_set_y(ui_timeHistory5, 2);
    lv_obj_set_align(ui_timeHistory5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_timeHistory5, "00.00");
    lv_obj_set_style_text_color(ui_timeHistory5, lv_color_hex(0xD5D5D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_timeHistory5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_timeHistory5, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_timeHistory5, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TDHistory5 = lv_label_create(ui_panelHistory5);
    lv_obj_set_width(ui_TDHistory5, 83);
    lv_obj_set_height(ui_TDHistory5, 20);
    lv_obj_set_x(ui_TDHistory5, -10);
    lv_obj_set_y(ui_TDHistory5, 6);
    lv_label_set_text(ui_TDHistory5, "--/--");
    lv_obj_set_style_text_color(ui_TDHistory5, lv_color_hex(0x00FF9A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TDHistory5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_TDHistory5, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TDHistory5, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_userHistory5 = lv_label_create(ui_panelHistory5);
    lv_obj_set_width(ui_userHistory5, 175);
    lv_obj_set_height(ui_userHistory5, 17);
    lv_obj_set_x(ui_userHistory5, 374);
    lv_obj_set_y(ui_userHistory5, -5);
    lv_label_set_text(ui_userHistory5, "Admin");
    lv_obj_set_style_text_color(ui_userHistory5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_userHistory5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_userHistory5, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_userHistory5, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_STDHistory5 = lv_label_create(ui_panelHistory5);
    lv_obj_set_width(ui_STDHistory5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_STDHistory5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_STDHistory5, -168);
    lv_obj_set_y(ui_STDHistory5, -17);
    lv_obj_set_align(ui_STDHistory5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_STDHistory5, "mg/dL");
    lv_obj_set_style_text_color(ui_STDHistory5, lv_color_hex(0xD5D5D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_STDHistory5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_STDHistory5, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_STDHistory5, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SBPMHisory5 = lv_label_create(ui_panelHistory5);
    lv_obj_set_width(ui_SBPMHisory5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SBPMHisory5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SBPMHisory5, -176);
    lv_obj_set_y(ui_SBPMHisory5, 26);
    lv_obj_set_align(ui_SBPMHisory5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SBPMHisory5, "BPM");
    lv_obj_set_style_text_color(ui_SBPMHisory5, lv_color_hex(0xD5D5D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SBPMHisory5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_SBPMHisory5, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SBPMHisory5, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BPMHistory5 = lv_label_create(ui_panelHistory5);
    lv_obj_set_width(ui_BPMHistory5, 43);
    lv_obj_set_height(ui_BPMHistory5, 20);
    lv_obj_set_x(ui_BPMHistory5, 26);
    lv_obj_set_y(ui_BPMHistory5, 50);
    lv_label_set_text(ui_BPMHistory5, "--");
    lv_obj_set_style_text_color(ui_BPMHistory5, lv_color_hex(0xF56570), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BPMHistory5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_BPMHistory5, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BPMHistory5, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_textDot5 = lv_label_create(ui_panelHistory5);
    lv_obj_set_width(ui_textDot5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_textDot5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_textDot5, 220);
    lv_obj_set_y(ui_textDot5, -6);
    lv_obj_set_align(ui_textDot5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_textDot5, ".");
    lv_obj_set_style_text_color(ui_textDot5, lv_color_hex(0xD5D5D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_textDot5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_textDot5, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_textDot5, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dateHistory5 = lv_label_create(ui_panelHistory5);
    lv_obj_set_width(ui_dateHistory5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dateHistory5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dateHistory5, 185);
    lv_obj_set_y(ui_dateHistory5, 1);
    lv_obj_set_align(ui_dateHistory5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dateHistory5, "14 mar");
    lv_obj_set_style_text_color(ui_dateHistory5, lv_color_hex(0xD5D5D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_dateHistory5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_dateHistory5, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_dateHistory5, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ImgButton3, ui_event_ImgButton3, LV_EVENT_ALL, NULL);

}

void ui_Screen2_screen_destroy(void)
{
    if(ui_Screen2) lv_obj_del(ui_Screen2);

    // NULL screen variables
    ui_Screen2 = NULL;
    ui_Panel3 = NULL;
    ui_Button3 = NULL;
    ui_namaText2 = NULL;
    ui_ImgButton3 = NULL;
    ui_Panel4 = NULL;
    ui_panelHistory1 = NULL;
    ui_timeHistory1 = NULL;
    ui_TDHistory1 = NULL;
    ui_userHistory1 = NULL;
    ui_STDHistory1 = NULL;
    ui_SBPMHisory1 = NULL;
    ui_BPMHistory1 = NULL;
    ui_textDot1 = NULL;
    ui_dateHistory1 = NULL;
    ui_panelHistory2 = NULL;
    ui_timeHistory2 = NULL;
    ui_TDHistory2 = NULL;
    ui_userHistory2 = NULL;
    ui_STDHistory2 = NULL;
    ui_SBPMHisory2 = NULL;
    ui_BPMHistory2 = NULL;
    ui_textDot2 = NULL;
    ui_dateHistory2 = NULL;
    ui_panelHistory3 = NULL;
    ui_timeHistory3 = NULL;
    ui_TDHistory3 = NULL;
    ui_userHistory3 = NULL;
    ui_STDHistory3 = NULL;
    ui_SBPMHisory3 = NULL;
    ui_BPMHistory3 = NULL;
    ui_textDot3 = NULL;
    ui_dateHistory3 = NULL;
    ui_panelHistory4 = NULL;
    ui_timeHistory4 = NULL;
    ui_TDHistory4 = NULL;
    ui_userHistory4 = NULL;
    ui_STDHistory4 = NULL;
    ui_SBPMHisory4 = NULL;
    ui_BPMHistory4 = NULL;
    ui_textDot4 = NULL;
    ui_dateHistory4 = NULL;
    ui_panelHistory5 = NULL;
    ui_timeHistory5 = NULL;
    ui_TDHistory5 = NULL;
    ui_userHistory5 = NULL;
    ui_STDHistory5 = NULL;
    ui_SBPMHisory5 = NULL;
    ui_BPMHistory5 = NULL;
    ui_textDot5 = NULL;
    ui_dateHistory5 = NULL;

}
