// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: PPG_UI

#ifndef UI_SCREEN2_H
#define UI_SCREEN2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen2
extern void ui_Screen2_screen_init(void);
extern void ui_Screen2_screen_destroy(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_namaText2;
extern void ui_event_ImgButton3(lv_event_t * e);
extern lv_obj_t * ui_ImgButton3;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_panelHistory1;
extern lv_obj_t * ui_timeHistory1;
extern lv_obj_t * ui_TDHistory1;
extern lv_obj_t * ui_userHistory1;
extern lv_obj_t * ui_STDHistory1;
extern lv_obj_t * ui_SBPMHisory1;
extern lv_obj_t * ui_BPMHistory1;
extern lv_obj_t * ui_textDot1;
extern lv_obj_t * ui_dateHistory1;
extern lv_obj_t * ui_panelHistory2;
extern lv_obj_t * ui_timeHistory2;
extern lv_obj_t * ui_TDHistory2;
extern lv_obj_t * ui_userHistory2;
extern lv_obj_t * ui_STDHistory2;
extern lv_obj_t * ui_SBPMHisory2;
extern lv_obj_t * ui_BPMHistory2;
extern lv_obj_t * ui_textDot2;
extern lv_obj_t * ui_dateHistory2;
extern lv_obj_t * ui_panelHistory3;
extern lv_obj_t * ui_timeHistory3;
extern lv_obj_t * ui_TDHistory3;
extern lv_obj_t * ui_userHistory3;
extern lv_obj_t * ui_STDHistory3;
extern lv_obj_t * ui_SBPMHisory3;
extern lv_obj_t * ui_BPMHistory3;
extern lv_obj_t * ui_textDot3;
extern lv_obj_t * ui_dateHistory3;
extern lv_obj_t * ui_panelHistory4;
extern lv_obj_t * ui_timeHistory4;
extern lv_obj_t * ui_TDHistory4;
extern lv_obj_t * ui_userHistory4;
extern lv_obj_t * ui_STDHistory4;
extern lv_obj_t * ui_SBPMHisory4;
extern lv_obj_t * ui_BPMHistory4;
extern lv_obj_t * ui_textDot4;
extern lv_obj_t * ui_dateHistory4;
extern lv_obj_t * ui_panelHistory5;
extern lv_obj_t * ui_timeHistory5;
extern lv_obj_t * ui_TDHistory5;
extern lv_obj_t * ui_userHistory5;
extern lv_obj_t * ui_STDHistory5;
extern lv_obj_t * ui_SBPMHisory5;
extern lv_obj_t * ui_BPMHistory5;
extern lv_obj_t * ui_textDot5;
extern lv_obj_t * ui_dateHistory5;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

