// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: PPG_UI

#include "ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_startButton = NULL;
lv_obj_t * ui_textIntruksi = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_riwayatButton = NULL;
lv_obj_t * ui_ppgChart = NULL;
lv_obj_t * ui_signalBar = NULL;
lv_obj_t * ui_actualBatt = NULL;
lv_obj_t * ui_percentBatt = NULL;
lv_obj_t * ui_userButton = NULL;
lv_obj_t * ui_textTD = NULL;
lv_obj_t * ui_satuanBPM = NULL;
lv_obj_t * ui_actualBPM = NULL;
lv_obj_t * ui_textSinyal = NULL;
lv_obj_t * ui_actualTime = NULL;
lv_obj_t * ui_textPPG = NULL;
lv_obj_t * ui_actualSignal = NULL;
lv_obj_t * ui_percentSignal = NULL;
lv_obj_t * ui_satuanTD = NULL;
lv_obj_t * ui_actualTD = NULL;
lv_obj_t * ui_heartImg = NULL;
lv_obj_t * ui_clockImg = NULL;
lv_obj_t * ui_batteryImg = NULL;
lv_obj_t * ui_Image3 = NULL;
// event funtions
void ui_event_riwayatButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen2_screen_init);
    }
}

void ui_event_userButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen3_screen_init);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x0B0A0F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Screen1, &ui_img_grid_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_startButton = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_startButton, 80);
    lv_obj_set_height(ui_startButton, 80);
    lv_obj_set_x(ui_startButton, 0);
    lv_obj_set_y(ui_startButton, 158);
    lv_obj_set_align(ui_startButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_startButton, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_startButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_startButton, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_startButton, lv_color_hex(0xDB57FC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_startButton, 225, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_startButton, lv_color_hex(0x00DCFD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_startButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_startButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_startButton, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_startButton, &ui_img_posisistop_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_startButton, lv_color_hex(0x00FFFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_startButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_startButton, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_startButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_startButton, &ui_img_posisistart_png, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_src(ui_startButton, &ui_img_posisistart_png, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_textIntruksi = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_textIntruksi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_textIntruksi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_textIntruksi, 0);
    lv_obj_set_y(ui_textIntruksi, 219);
    lv_obj_set_align(ui_textIntruksi, LV_ALIGN_CENTER);
    lv_label_set_text(ui_textIntruksi, "Letakkan jari pada sensor");
    lv_obj_set_style_text_font(ui_textIntruksi, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel1, 700);
    lv_obj_set_height(ui_Panel1, 100);
    lv_obj_set_x(ui_Panel1, 0);
    lv_obj_set_y(ui_Panel1, 55);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel1, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x12121A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel1, lv_color_hex(0x12121A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_riwayatButton = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_riwayatButton, 60);
    lv_obj_set_height(ui_riwayatButton, 60);
    lv_obj_set_x(ui_riwayatButton, -130);
    lv_obj_set_y(ui_riwayatButton, 158);
    lv_obj_set_align(ui_riwayatButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_riwayatButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_riwayatButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_riwayatButton, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_riwayatButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_riwayatButton, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_riwayatButton, &ui_img_riwayat_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ppgChart = lv_chart_create(ui_Screen1);
    lv_obj_set_width(ui_ppgChart, 700);
    lv_obj_set_height(ui_ppgChart, 130);
    lv_obj_set_x(ui_ppgChart, 0);
    lv_obj_set_y(ui_ppgChart, -87);
    lv_obj_set_align(ui_ppgChart, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_ppgChart, LV_CHART_TYPE_LINE);
    lv_chart_set_range(ui_ppgChart, LV_CHART_AXIS_PRIMARY_Y, 0, 262143);
    lv_chart_set_div_line_count(ui_ppgChart, 4, 6);
    lv_chart_set_axis_tick(ui_ppgChart, LV_CHART_AXIS_PRIMARY_X, 10, 5, 10, 2, true, 50);
    lv_chart_set_axis_tick(ui_ppgChart, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 10, 2, true, 50);
    lv_chart_set_axis_tick(ui_ppgChart, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 2, false, 25);
    lv_chart_series_t * ui_ppgChart_series_1 = lv_chart_add_series(ui_ppgChart, lv_color_hex(0x00EDFF),
                                                                   LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_ppgChart_series_1_array[] = { 0 };
    lv_chart_set_ext_y_array(ui_ppgChart, ui_ppgChart_series_1, ui_ppgChart_series_1_array);
    lv_obj_set_style_radius(ui_ppgChart, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ppgChart, lv_color_hex(0x12121A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ppgChart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ppgChart, lv_color_hex(0x12121A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ppgChart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_ppgChart, &lv_font_montserrat_8, LV_PART_TICKS | LV_STATE_DEFAULT);

    ui_signalBar = lv_bar_create(ui_Screen1);
    lv_bar_set_value(ui_signalBar, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_signalBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_signalBar, 284);
    lv_obj_set_height(ui_signalBar, 12);
    lv_obj_set_x(ui_signalBar, 188);
    lv_obj_set_y(ui_signalBar, 49);
    lv_obj_set_align(ui_signalBar, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_signalBar, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_signalBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_signalBar, lv_color_hex(0x00FF0F), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_signalBar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_signalBar, 120, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_signalBar, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_actualBatt = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_actualBatt, 37);
    lv_obj_set_height(ui_actualBatt, 19);
    lv_obj_set_x(ui_actualBatt, 664);
    lv_obj_set_y(ui_actualBatt, 29);
    lv_label_set_text(ui_actualBatt, "100");
    lv_obj_set_style_text_color(ui_actualBatt, lv_color_hex(0x00FF9A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_actualBatt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_actualBatt, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_actualBatt, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_percentBatt = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_percentBatt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_percentBatt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_percentBatt, 314);
    lv_obj_set_y(ui_percentBatt, -201);
    lv_obj_set_align(ui_percentBatt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_percentBatt, "%");
    lv_obj_set_style_text_font(ui_percentBatt, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_userButton = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_userButton, 60);
    lv_obj_set_height(ui_userButton, 60);
    lv_obj_set_x(ui_userButton, 130);
    lv_obj_set_y(ui_userButton, 158);
    lv_obj_set_align(ui_userButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_userButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_userButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_userButton, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_userButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_userButton, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_userButton, &ui_img_user_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_textTD = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_textTD, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_textTD, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_textTD, -270);
    lv_obj_set_y(ui_textTD, 30);
    lv_obj_set_align(ui_textTD, LV_ALIGN_CENTER);
    lv_label_set_text(ui_textTD, "Tekanan Darah");
    lv_obj_set_style_text_color(ui_textTD, lv_color_hex(0xB3B3B3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_textTD, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_textTD, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_satuanBPM = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_satuanBPM, 44);
    lv_obj_set_height(ui_satuanBPM, 19);
    lv_obj_set_x(ui_satuanBPM, 158);
    lv_obj_set_y(ui_satuanBPM, 84);
    lv_obj_set_align(ui_satuanBPM, LV_ALIGN_CENTER);
    lv_label_set_text(ui_satuanBPM, "BPM");
    lv_obj_set_style_text_color(ui_satuanBPM, lv_color_hex(0xD5D5D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_satuanBPM, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_satuanBPM, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_satuanBPM, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_actualBPM = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_actualBPM, 48);
    lv_obj_set_height(ui_actualBPM, 19);
    lv_obj_set_x(ui_actualBPM, 471);
    lv_obj_set_y(ui_actualBPM, 314);
    lv_label_set_text(ui_actualBPM, "--");
    lv_obj_set_style_text_color(ui_actualBPM, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_actualBPM, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_actualBPM, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_actualBPM, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_textSinyal = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_textSinyal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_textSinyal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_textSinyal, 68);
    lv_obj_set_y(ui_textSinyal, 24);
    lv_obj_set_align(ui_textSinyal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_textSinyal, "Sinyal");
    lv_obj_set_style_text_color(ui_textSinyal, lv_color_hex(0xB3B3B3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_textSinyal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_textSinyal, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_actualTime = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_actualTime, 62);
    lv_obj_set_height(ui_actualTime, 16);
    lv_obj_set_x(ui_actualTime, 661);
    lv_obj_set_y(ui_actualTime, 317);
    lv_label_set_text(ui_actualTime, "00:00");
    lv_obj_set_style_text_color(ui_actualTime, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_actualTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_actualTime, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_actualTime, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_textPPG = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_textPPG, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_textPPG, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_textPPG, -320);
    lv_obj_set_y(ui_textPPG, -130);
    lv_obj_set_align(ui_textPPG, LV_ALIGN_CENTER);
    lv_label_set_text(ui_textPPG, "PPG");
    lv_obj_set_style_text_color(ui_textPPG, lv_color_hex(0xB3B3B3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_textPPG, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_textPPG, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_actualSignal = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_actualSignal, 31);
    lv_obj_set_height(ui_actualSignal, 12);
    lv_obj_set_x(ui_actualSignal, 673);
    lv_obj_set_y(ui_actualSignal, 258);
    lv_label_set_text(ui_actualSignal, "100");
    lv_obj_set_style_text_color(ui_actualSignal, lv_color_hex(0x00FF9A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_actualSignal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_actualSignal, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_actualSignal, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_percentSignal = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_percentSignal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_percentSignal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_percentSignal, 317);
    lv_obj_set_y(ui_percentSignal, 27);
    lv_obj_set_align(ui_percentSignal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_percentSignal, "%");
    lv_obj_set_style_text_font(ui_percentSignal, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_satuanTD = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_satuanTD, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_satuanTD, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_satuanTD, -179);
    lv_obj_set_y(ui_satuanTD, 78);
    lv_obj_set_align(ui_satuanTD, LV_ALIGN_CENTER);
    lv_label_set_text(ui_satuanTD, "mmHg");
    lv_obj_set_style_text_color(ui_satuanTD, lv_color_hex(0xD5D5D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_satuanTD, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_satuanTD, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_satuanTD, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_actualTD = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_actualTD, 67);
    lv_obj_set_height(ui_actualTD, 16);
    lv_obj_set_x(ui_actualTD, 108);
    lv_obj_set_y(ui_actualTD, 309);
    lv_label_set_text(ui_actualTD, "--/--");
    lv_obj_set_style_text_color(ui_actualTD, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_actualTD, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_actualTD, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_actualTD, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_heartImg = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_heartImg, &ui_img_hearticon_png);
    lv_obj_set_width(ui_heartImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_heartImg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_heartImg, 62);
    lv_obj_set_y(ui_heartImg, 82);
    lv_obj_set_align(ui_heartImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_heartImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_heartImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_heartImg, 70);

    ui_clockImg = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_clockImg, &ui_img_clockicon_png);
    lv_obj_set_width(ui_clockImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_clockImg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_clockImg, 229);
    lv_obj_set_y(ui_clockImg, 85);
    lv_obj_set_align(ui_clockImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_clockImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_clockImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_clockImg, 70);

    ui_batteryImg = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_batteryImg, &ui_img_batteryicon_png);
    lv_obj_set_width(ui_batteryImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_batteryImg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_batteryImg, 352);
    lv_obj_set_y(ui_batteryImg, -202);
    lv_obj_set_align(ui_batteryImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_batteryImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_batteryImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_batteryImg, 90);

    ui_Image3 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image3, &ui_img_logo_kmnksjkt3_png);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image3, -256);
    lv_obj_set_y(ui_Image3, -195);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image3, 130);

    lv_obj_add_event_cb(ui_riwayatButton, ui_event_riwayatButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_userButton, ui_event_userButton, LV_EVENT_ALL, NULL);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_startButton = NULL;
    ui_textIntruksi = NULL;
    ui_Panel1 = NULL;
    ui_riwayatButton = NULL;
    ui_ppgChart = NULL;
    ui_signalBar = NULL;
    ui_actualBatt = NULL;
    ui_percentBatt = NULL;
    ui_userButton = NULL;
    ui_textTD = NULL;
    ui_satuanBPM = NULL;
    ui_actualBPM = NULL;
    ui_textSinyal = NULL;
    ui_actualTime = NULL;
    ui_textPPG = NULL;
    ui_actualSignal = NULL;
    ui_percentSignal = NULL;
    ui_satuanTD = NULL;
    ui_actualTD = NULL;
    ui_heartImg = NULL;
    ui_clockImg = NULL;
    ui_batteryImg = NULL;
    ui_Image3 = NULL;

}
